<?php
/** @var MagentoTest\Modulemtest\Block\Main $block*/
?>
<?php foreach ($block->getMain()->getItems() as $item): ?>
    <span>Name: <?= $item->getName();?></span><br/>
    <span>Email: <?= $item->getEmail();?></span><br/>
    <span>Content: <?= $item->getContent();?></span>
    <span>Season: <?= $item->getSeason();?></span>
    ------------------------------------------------------
<?php endforeach; ?>