<?php
/** @var MagentoTest\Modulemtest\Block\Main $block*/
?>
<?php foreach ($block->getMain()->getItems() as $item): ?>
    <span>Name: <?php echo $item->getName();?></span><br/>
    <span>Email: <?php echo $item->getEmail();?></span><br/>
    <span>Content: <?php echo $item->getContent();?></span><br/>
    <span>Season: <?php echo $item->getSeason();?></span><br/>
    ------------------------------------------------------<br/>
<?php endforeach; ?>